name: Build and deploy the Angular App to GitHub and start pentesting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  owasp-pentesting-github-action:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
      
      - name: Install NPM dependencies
        run: npm install
      
      - name: Build Angular App
        run: npm run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/live-stream-angular-pentesting
      
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "https://gregorbiswanger.github.io/live-stream-angular-pentesting"
